language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5;

  # Also use it if that's what we're going for
  - export CC=gcc-5 &&
    export CXX="g++-5";
